config/routes.rb
Sportsume::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users

  resources :organizations
  
  resources :teams do
    resources :memberships
  end
  

  

  
  
devise_scope :user do
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
end

  root :to => "home#index"

  get '/sign_out', :to => 'sessions#destroy'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :is_coach, :jersey_number, :position, :stats, :team_id, :user_id

  belongs_to :user
  belongs_to :team


end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.json
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(params[:membership])
    @team = params[:team_id]
    

    respond_to do |format|
      if @membership.save
        # format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        # format.json { render json: @membership, status: :created, location: @membership }
        format.html { redirect_to team_path(@team), notice: 'Membership was successfully created.' }

      else
        format.html { render action: "new" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<% @team = Team.find(params[:team_id]) %>

<%= semantic_form_for @membership, :url => "/teams/#{@team.id}/memberships" do |f| %>
  <%= f.inputs do %>
   <%= f.input :team_id, :value => params[:team_id], :as => :hidden %>
    <%= f.input :position %>
    <%= f.input :jersey_number %>
    <%= f.input :stats %>
    <%= f.input :is_coach %>
    <%= f.input :user_id, :value => current_user.id, :as => :hidden %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <tr>
    <th>Position</th>
    <th>Jersey number</th>
    <th>Stats</th>
    <th>Is coach</th>
    <th>Team</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.position %></td>
    <td><%= membership.jersey_number %></td>
    <td><%= membership.stats %></td>
    <td><%= membership.is_coach %></td>
    <td><%= membership.team_id %></td>
    <td><%= membership.user_id %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @membership.position %>
</p>

<p>
  <b>Jersey number:</b>
  <%= @membership.jersey_number %>
</p>

<p>
  <b>Stats:</b>
  <%= @membership.stats %>
</p>

<p>
  <b>Is coach:</b>
  <%= @membership.is_coach %>
</p>

<p>
  <b>Team:</b>
  <%= @membership.team_id %>
</p>

<p>
  <b>User:</b>
  <%= @membership.user_id %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>