config/routes.rb
Sportsume::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users

  resources :organizations
  
  resources :teams do
    resources :memberships
  end
  

  

  
  
devise_scope :user do
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
end

  root :to => "home#index"

  get '/sign_out', :to => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :city, :country, :dob, :favorite_sport, :height, :icon_image, :name, :state, :weight
  # attr_accessible :title, :body

  has_many :memberships
  has_many :teams, :through => :memberships

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = self.find_by_email(data.email)
      user
    else # Create a user with a stub password. 
      self.create(:email => data.email, :password => Devise.friendly_token[0,20]) 
    end
  end

  #def self.new_with_session(params, session)
  # super.tap do |user|
  #    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #      user.email = data["email"]
  #    end
  #  end
  #end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  

  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    # Or alternatively,
    # raise ActionController::RoutingError.new('Not Found')
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.number_field :dob %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :favorite_sport %><br />
    <%= f.text_field :favorite_sport %>
  </div>
  <div class="field">
    <%= f.label :icon_image %><br />
    <%= f.text_field :icon_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Dob</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Favorite sport</th>
    <th>Icon image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.dob %></td>
    <td><%= user.city %></td>
    <td><%= user.state %></td>
    <td><%= user.country %></td>
    <td><%= user.height %></td>
    <td><%= user.weight %></td>
    <td><%= user.favorite_sport %></td>
    <td><%= user.icon_image %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @user.dob %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>State:</b>
  <%= @user.state %>
</p>

<p>
  <b>Country:</b>
  <%= @user.country %>
</p>

<p>
  <b>Height:</b>
  <%= @user.height %>
</p>

<p>
  <b>Weight:</b>
  <%= @user.weight %>
</p>

<p>
  <b>Favorite sport:</b>
  <%= @user.favorite_sport %>
</p>

<p>
  <b>Icon image:</b>
  <%= @user.icon_image %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<br><br>

  <b>Teams (years):</b>
    <br>
  <table>
  <tr>
    <th>Year</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>Achievements</th>
    <th width='20px'></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


  <% @user.teams.each do |team| %>
  <tr>
    <td><%= team.year %></td>
    <td><%= team.wins %></td>
    <td><%= team.losses %></td>
    <td><%= team.achievements %></td>
    <td width='20px'></td>
    <td><%= link_to 'Show', team %></td>
    <td><%= link_to 'Edit', edit_team_path(team) %></td>
    <td><%= link_to 'Destroy', team, confirm: 'Are you sure?',
                                     method: :delete %></td>
  </tr>
<% end %>
  </table>