config/routes.rb
Sportsume::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users

  resources :organizations
  
  resources :teams do
    resources :memberships
  end
  

  

  
  
devise_scope :user do
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
end

  root :to => "home#index"

  get '/sign_out', :to => 'sessions#destroy'

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :teams, dependent: :destroy
  
  attr_accessible :level, :location, :mascot, :name, :sport
  


end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= semantic_form_for(@organization) do |f| %>

  <%= f.inputs do %>
      <%= f.input :name %>
      <%= f.input :level, :as => :select, :collection => ["Pro", "College", "High School"] %>
      <%= f.input :mascot %>
      <%= f.input :sport %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :button %>
    <%= f.action :cancel, :as => :link %>
  <% end %>






<% end %>

app/views/organizations/_form.html.haml
= semantic_form_for(@organization) do |f|
  = f.inputs do
    = f.input :name
    = f.input :level, :as => :select, :collection => ["Pro", "College", "High School"]
    = f.input :mascot
    = f.input :sport
  = f.actions do
    = f.action :submit, :as => :button
    = f.action :cancel, :as => :link

app/views/organizations/edit.html.haml
%h1 Editing organization
= render 'form'
= link_to 'Show', @organization
|
\#{link_to 'Back', organizations_path}

app/views/organizations/index.html.haml
%h1 Listing organizations
%table
  %tr
    %th Name
    %th Mascot
    %th Location
    %th Level
    %th Sport
    %th
    %th
    %th
  - @organizations.each do |organization|
    %tr
      %td= organization.name
      %td= organization.mascot
      %td= organization.location
      %td= organization.level
      %td= organization.sport
      %td= link_to 'Show', organization
      %td= link_to 'Edit', edit_organization_path(organization)
      %td= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h1 New organization
= render 'form'
= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%h2
  = @organization.name
%p
  %b Mascot:
  = @organization.mascot
%p
  %b Location:
  = @organization.location
%p
  %b Level:
  = @organization.level
%p
  %b Sport:
  = @organization.sport
= link_to 'Edit', edit_organization_path(@organization)
|
\#{link_to 'Back', organizations_path}
%br
  %br
    %b Teams (years):
    %br
      %table
        %tr
          %th Year
          %th Wins
          %th Losses
          %th Achievements
          %th{:width => "20px"}
          %th
          %th
          %th
        - @organization.teams.each do |team|
          %tr
            %td= team.year
            %td= team.wins
            %td= team.losses
            %td= team.achievements
            %td{:width => "20px"}
            %td= link_to 'Show', team
            %td= link_to 'Edit', edit_team_path(team)
            %td= link_to 'Destroy', team, confirm: 'Are you sure?', |
                method: :delete        


  